import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { and, clusterIndexes, clusters, createDatabase, eq, organizations } from "../src/db";
import { databaseUrl } from "./helpers";

// `cluster_indexes` identity, after `hidden` left it (#496).
//
// The claim under test is a database one — a generated digest and a unique index
// — so it is asserted against a real postgres rather than against a copy of the
// expression in JS. That is the whole point: the digest is generated BY the
// database precisely so the writer cannot disagree with it, and a test that
// recomputed it here would be the disagreement it exists to prevent.
//
// What went wrong without this: hiding an index changed its spec, which changed
// its digest, which minted a second dimension row and started its usage history
// over — on the hosted deployment, 26 duplicate identities differing in nothing
// else, and 25 of them on the cluster where one pass hid 24 indexes. The history
// an observe window reads is the history the hide truncated.

const ORG = "1a7e0000-0000-4000-8000-00000000f002";
const CLUSTER = "1a7e0000-0000-4000-8000-00000000c002";

let db: ReturnType<typeof createDatabase>;

const spec = (extra: Record<string, unknown>): Record<string, unknown> => ({
  name: "a_1",
  keys: [{ field: "a", direction: 1 }],
  unique: false,
  sparse: false,
  ...extra,
});

const insert = (indexName: string, body: Record<string, unknown>): Promise<unknown> =>
  db
    .insert(clusterIndexes)
    .values({ clusterId: CLUSTER, database: "app", collection: "orders", indexName, spec: body });

beforeAll(async () => {
  db = createDatabase(databaseUrl(), 2);
  await db
    .insert(organizations)
    .values({ id: ORG, name: "Dimension", slug: `dimension-${process.pid}`, plan: "PRO" })
    .onConflictDoNothing();
  await db
    .insert(clusters)
    .values({
      id: CLUSTER,
      orgId: ORG,
      name: "dimension",
      connectionMode: "HOSTED_DIRECT",
      sealedDek: Buffer.from([0]),
      sealedData: Buffer.from([0]),
      engine: "MONGODB",
    })
    .onConflictDoNothing();
  await db.delete(clusterIndexes).where(eq(clusterIndexes.clusterId, CLUSTER));
});

afterAll(async () => {
  await db.delete(clusterIndexes).where(eq(clusterIndexes.clusterId, CLUSTER));
  await db.delete(clusters).where(eq(clusters.id, CLUSTER));
  await db.delete(organizations).where(eq(organizations.id, ORG));
});

describe("cluster_indexes identity", () => {
  it("is the same index once it has been hidden", async () => {
    await insert("a_1", spec({ hidden: false }));
    // The row this product creates when it hides one. Under the old digest it
    // was a second identity; now it is the same one, and the insert is refused.
    await expect(insert("a_1", spec({ hidden: true }))).rejects.toThrow();
    const rows = await db
      .select({ digest: clusterIndexes.specDigest })
      .from(clusterIndexes)
      .where(eq(clusterIndexes.clusterId, CLUSTER));
    expect(rows).toHaveLength(1);
  });

  it("is a different index when the spec really changes", async () => {
    await insert("b_1", spec({ name: "b_1", hidden: false }));
    // `unique` is a shape. Two rows here is correct and stays correct.
    await insert("b_1", spec({ name: "b_1", hidden: false, unique: true }));
    const rows = await db
      .select({ digest: clusterIndexes.specDigest })
      .from(clusterIndexes)
      .where(and(eq(clusterIndexes.clusterId, CLUSTER), eq(clusterIndexes.indexName, "b_1")));
    expect(rows).toHaveLength(2);
    expect(new Set(rows.map((row) => row.digest)).size).toBe(2);
  });

  it("gives the two hidden states one digest, and only because of `hidden`", async () => {
    await insert("c_1", spec({ name: "c_1", hidden: false }));
    const [visible] = await db
      .select({ digest: clusterIndexes.specDigest })
      .from(clusterIndexes)
      .where(and(eq(clusterIndexes.clusterId, CLUSTER), eq(clusterIndexes.indexName, "c_1")));
    await db
      .delete(clusterIndexes)
      .where(and(eq(clusterIndexes.clusterId, CLUSTER), eq(clusterIndexes.indexName, "c_1")));
    await insert("c_1", spec({ name: "c_1", hidden: true }));
    const [hiddenRow] = await db
      .select({ digest: clusterIndexes.specDigest, spec: clusterIndexes.spec })
      .from(clusterIndexes)
      .where(and(eq(clusterIndexes.clusterId, CLUSTER), eq(clusterIndexes.indexName, "c_1")));
    expect(hiddenRow?.digest).toBe(visible?.digest);
    // Still STORED, just not part of the identity — analysis/redundancy.ts and
    // analysis/purge.ts both read it off the spec.
    expect(hiddenRow?.spec.hidden).toBe(true);
  });
});
